function [W, wellIx] = gen_wells(G, rock, R_inj)
%GEN_WELLS Summary of this function goes here
%   Detailed explanation goes here

    wellIx = [20,20,44,44; 20,44,20,44]';
    num_wells = size(wellIx, 1);

    W = [];
    for i=1:num_wells
        W = verticalWell(W, G, rock, wellIx(i,1), wellIx(i,2), [], ...
                         'InnerProduct' , 'ip_tpf' , ...
                         'Type'         , 'rate'   , ...
                         'Sign'         , 1        , ...
                         'Val'          , R_inj    , ...
                         'comp_i'       , [0,1]    , ...
                         'Radius'       , 0.1      , ...
                         'refDepth'     , []       , ...
                         'name'         , ['I', int2str(i)]);
    end

end